<?php

namespace AppBundle\Repository;

/**
 * AnswerToQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerToQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
