<?php

namespace AppBundle\Repository;

/**
 * CompanyMemberFunctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyMemberFunctionRepository extends \Doctrine\ORM\EntityRepository
{
}
