<?php

namespace AppBundle\Repository;

/**
 * CompanySectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanySectorRepository extends \Doctrine\ORM\EntityRepository
{
}
