<?php

namespace AppBundle\Repository;

/**
 * CompanyMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
