<?php

namespace AppBundle\Repository;

/**
 * CompanyFunctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyFunctionRepository extends \Doctrine\ORM\EntityRepository
{
}
