<?php

namespace AppBundle\Repository;

/**
 * TopicTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
