<?php

namespace AppBundle\Repository;

/**
 * UserSectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSectorRepository extends \Doctrine\ORM\EntityRepository
{
}
