app:
   resource: "@AppBundle/Controller"
   type:     annotation

logout:
   path: /logout

fos_user:
   resource: "@FOSUserBundle/Resources/config/routing/all.xml"

home:
  path:     /dashboard/home
  defaults: { _controller: AppBundle:Dashboard:index }


_errors:
  resource: "@TwigBundle/Resources/config/routing/errors.xml"
  prefix:   /_error