app_company_member:
    resource: "@AppBundle/Controller/CompanyMemberController.php"
    type:     annotation

app_company_member_function:
    resource: "@AppBundle/Controller/CompanyMemberFunctionController.php"
    type:     annotation

app_ranking:
    resource: "@AppBundle/Controller/RankingController.php"
    type:     annotation

app_question:
    resource: "@AppBundle/Controller/QuestionController.php"
    type:     annotation

app_company:
    resource: "@AppBundle/Controller/CompanyController.php"
    type:     annotation

app:
   resource: "@AppBundle/Controller"
   type:     annotation

logout:
   path: /logout

fos_user:
   resource: "@FOSUserBundle/Resources/config/routing/all.xml"

home:
  path:     /dashboard/home
  defaults: { _controller: AppBundle:Dashboard:index }


_errors:
  resource: "@TwigBundle/Resources/config/routing/errors.xml"
  prefix:   /_error